### ISSUE TITLE
Warning while build 

### ISSUE THREAD

**Issue by DamianLaczynski** [KeepIt-Up/MagJob-backend#1] opened 2024-03-05 22:03 UTC
2024-03-03T13:23:03.990+01:00  WARN 11496 --- [           main] org.hibernate.orm.deprecation            : HHH90000025: PostgreSQLDialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)

2024-03-03T13:23:05.035+01:00  WARN 11496 --- [           main] o.h.t.s.i.ExceptionHandlerLoggedImpl     : GenerationTarget encountered exception accepting command : Error executing DDL "create table invitations (id numeric(38,0) not null, date_of_creation timestamp(6) with time zone, is_active boolean not null, organization_id numeric(38,0), user_id numeric(38,0), primary key (id))" via JDBC [BŁĄD: odmowa dostępu do schematu public
  Pozycja: 14]

**Comment by kmonieczny** [comment] 2024-10-20 11:52
I couldn't reproduce this issue while running the backend on the main branch, so I'll go ahead and close it.

**Closed by kmonieczny** 2024-10-20 11:52 UTC
